SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE PA_CONSULTAR_TODO_MA_MI (@MAMI CHAR(2))
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @M CHAR(2);
	SET @M=@MAMI;

	IF (@M = NULL OR @M NOT IN ('MA','MI'))
		SET @M='MA';
	
	 IF (@M='MA')
	 BEGIN
			SELECT CONCAT(ID_LIBRO,')') AS 'NO.', UPPER(TITULO) AS TÍTULO, UPPER(AUTOR) AS 'AUTOR', UPPER(EDITORIAL) AS 'EDITORIAL', CONCAT('Q.',PRECIO) AS 'PRECIO' 
			INTO #TEMP_LIBROS_MA
			FROM LIBROS
			SELECT * FROM #TEMP_LIBROS_MA
	 END
	 ELSE IF(@M='MI')
	 BEGIN
			SELECT CONCAT(ID_LIBRO,')') AS 'NO.', LOWER(TITULO) AS TÍTULO, LOWER(AUTOR) AS 'AUTOR', LOWER(EDITORIAL) AS 'EDITORIAL', CONCAT('Q.',PRECIO) AS 'PRECIO' 
			INTO #TEMP_LIBROS_MI FROM LIBROS
			SELECT * FROM #TEMP_LIBROS_MI 
	 END		
	
END
GO
